[package]
name = "foxmarks"
version = "1.0.0"
authors = ["zer0-x"]
edition = "2021"
description = "A CLI read-only interface for firefox's bookmarks and history."
readme = "README.md"
homepage = "https://github.com/zer0-x/foxmarks"
repository = "https://github.com/zer0-x/foxmarks.git"
license = "GPL-3.0"
keywords = ["firefox", "bookmarks", "history", "cli"]
categories = ["command-line-utilities", "database-implementations"]
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = true

[dependencies]
rusqlite = "0.28.0"
tempfile = "3.3.0"
configparser = "3.0.1"
dirs = "4.0.0"
clap = "4.0.2"

[build-dependencies]
clap = "4.0.2"
clap_complete = "4.0.1"
